//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RussianDatingApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgeCategory
    {
        public AgeCategory()
        {
            this.UserProfile = new HashSet<UserProfile>();
        }
    
        public int AgeCategoryID { get; set; }
        public int AgeFrom { get; set; }
        public int AgeTo { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<UserProfile> UserProfile { get; set; }
    }
}
