//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RussianDatingApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnerPreference
    {
        public int PreferenceID { get; set; }
        public int ProfileID { get; set; }
        public Nullable<int> MinAge { get; set; }
        public Nullable<int> MaxAge { get; set; }
        public Nullable<int> MinHeight { get; set; }
        public Nullable<int> MaxHeight { get; set; }
        public Nullable<int> ZodiacSignID { get; set; }
        public string Gender { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
        public virtual ZodiacSign ZodiacSign { get; set; }
    }
}
