//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RussianDatingApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registration
    {
        public Registration()
        {
            this.UserAccount = new HashSet<UserAccount>();
            this.UserProfile = new HashSet<UserProfile>();
        }
    
        public int RegistrationID { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
    
        public virtual ICollection<UserAccount> UserAccount { get; set; }
        public virtual ICollection<UserProfile> UserProfile { get; set; }
    }
}
