//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RussianDatingApp.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RussianDatingAppEntities : DbContext
    {
        public RussianDatingAppEntities()
            : base("name=RussianDatingAppEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AgeCategory> AgeCategory { get; set; }
        public DbSet<City> City { get; set; }
        public DbSet<PartnerPreference> PartnerPreference { get; set; }
        public DbSet<Registration> Registration { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<UserAccount> UserAccount { get; set; }
        public DbSet<UserProfile> UserProfile { get; set; }
        public DbSet<ZodiacSign> ZodiacSign { get; set; }



    }

}
