//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RussianDatingApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        public UserProfile()
        {
            this.PartnerPreference = new HashSet<PartnerPreference>();
            this.UserAccount = new HashSet<UserAccount>();
        }
    
        public int ProfileID { get; set; }
        public int RegistrationID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public System.DateTime BirthDate { get; set; }
        public string Gender { get; set; }
        public string InterestedInGender { get; set; }
        public int CityID { get; set; }
        public string AboutText { get; set; }
        public Nullable<int> ZodiacSignID { get; set; }
        public Nullable<int> AgeCategoryID { get; set; }
        public Nullable<bool> HasPhoto { get; set; }
        public Nullable<bool> IsVerified { get; set; }
    
        public virtual AgeCategory AgeCategory { get; set; }
        public virtual City City { get; set; }
        public virtual ICollection<PartnerPreference> PartnerPreference { get; set; }
        public virtual Registration Registration { get; set; }
        public virtual ICollection<UserAccount> UserAccount { get; set; }
        public virtual ZodiacSign ZodiacSign { get; set; }
        public virtual ZodiacSign ZodiacSign1 { get; set; }
    }
}
