//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RussianDatingApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZodiacSign
    {
        public ZodiacSign()
        {
            this.PartnerPreference = new HashSet<PartnerPreference>();
            this.UserProfile = new HashSet<UserProfile>();
            this.UserProfile1 = new HashSet<UserProfile>();
        }
    
        public int ZodiacSignID { get; set; }
        public string Name { get; set; }
        public string RussianName { get; set; }
    
        public virtual ICollection<PartnerPreference> PartnerPreference { get; set; }
        public virtual ICollection<UserProfile> UserProfile { get; set; }
        public virtual ICollection<UserProfile> UserProfile1 { get; set; }
    }
}
